# Site settings
title: Culture Code
header-img: img/home-bg.jpg
email: culture.coding@gmail.com
description: ""
baseurl:
url:
twitter_username:
github_username:

# Build settings
markdown: kramdown
kramdown:
  input: GFM
extension: redcarpet
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
